apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /var/folders/ct/h5ht7gz11jg41b39fwncrx5h0000gn/T/go-build4026715356/b001/exe/main
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
