apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /var/folders/ct/h5ht7gz11jg41b39fwncrx5h0000gn/T/go-build4026715356/b001/exe/main
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /var/folders/ct/h5ht7gz11jg41b39fwncrx5h0000gn/T/go-build4026715356/b001/exe/main
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-poc-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: tuna/docker-counter23
          name: web
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
